/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActiveVocab: typeof import('./components/Portal.vue')['default']
    ActiveVocabulary: typeof import('./components/ActiveVocabulary.vue')['default']
    AddEssay: typeof import('./components/AddEssay.vue')['default']
    AddEssayModal: typeof import('./views/essay/AddEssayModal.vue')['default']
    ArticleDetail: typeof import('./components/ArticleDetail.vue')['default']
    ArticleList: typeof import('./components/ArticleList.vue')['default']
    ContentArea: typeof import('./components/layout/ContentArea.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableC: typeof import('element-plus/es')['ElTableC']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EssayDetail: typeof import('./components/EssayDetail.vue')['default']
    EssayDetailModal: typeof import('./components/EssayDetailModal.vue')['default']
    EssayInput: typeof import('./components/essay/EssayInput.vue')['default']
    EssayList: typeof import('./components/EssayList.vue')['default']
    FeedbackTable: typeof import('./components/FeedbackTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InnerTopBar: typeof import('./components/layout/InnerTopBar.vue')['default']
    LoginButton: typeof import('./components/layout/LoginButton.vue')['default']
    MainLayout: typeof import('./components/MainLayout.vue')['default']
    MappingCard: typeof import('./components/essay/MappingGridCard.vue')['default']
    MappingGridCard: typeof import('./components/essay/MappingGridCard.vue')['default']
    Portal: typeof import('./components/Portal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SentenceCard: typeof import('./components/essay/SentenceCard.vue')['default']
    SideBar: typeof import('./components/layout/SideBar.vue')['default']
    Toast: typeof import('./components/layout/Toast.vue')['default']
    TopBar: typeof import('./components/layout/TopBar.vue')['default']
    VocabularyTable: typeof import('./components/ActiveVocabulary.vue')['default']
    WordInput: typeof import('./components/WordInput.vue')['default']
  }
}
